from tkinter import *
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
Label(root,text=" ").pack()
Label(root,text=" ").pack()
bus=PhotoImage(file='.\\Bus_for_project.png')
Label(root,image=bus).pack()
Label(root,text=" ").pack()
Label(root,text="Online Bus Booking System",bg='light blue',fg='Red',font=('Allice',25)).pack()
Label(root,text=" ").pack()
Label(root,text=" ").pack()
Label(root,text="Name: Vinayak Sharma",fg='blue',font=('Allice',15)).pack()
Label(root,text=" ").pack()
Label(root,text=" ").pack()
Label(root,text="Er.No: 211B349",fg='blue',font=('Allice',15)).pack()
Label(root,text=" ").pack()
Label(root,text=" ").pack()
Label(root,text="Mobile: 8979898165",fg='blue',font=('Allice',15)).pack()
Label(root,text=" ").pack()
Label(root,text=" ").pack()
Label(root,text=" ").pack()
Label(root,text="Submitted to : Dr.Mahesh Kumar",bg='light blue',fg='red',font=('Allice',15)).pack()
Label(root,text="Project Based Learning",fg='red',font=('Allice',15)).pack()
Label(root,text=" ").pack()
Label(root,text=" ").pack()
Label(root,text="Press any key to proceed",fg='black',font=('Allice',11)).pack()
def close(e=1):
    root.destroy()
    import user
root.bind('<KeyPress>',close)
root.mainloop()
